### PR TITLE
Add gemeente rozenburg

### PR DESCRIPTION
**Pull request by lkeijser**
Added Rozenburg

### CODE REVIEW

**Comment by lkeijser** [comment]
Creating a pull request is still pretty new to me, so please let me know if I should change something.

**Comment by heyajohnny** [comment]
Thnx for the Pull request! :)
Since Rozenburg is part of Rotterdam and not an official 'gemeente' I have only 2 comments: 
Can you...
1. Change 'Rozenburg' in the Readme to 'Rotterdam Rozenburg'
2. Change 'rozenburg' in the sensor.py to 'rotterdam rozenburg'

And I have 1 question:
1. why did you change "wsa_calendar" to "e7ad65e902" in irado.py? Didn't the "364b570c83" work?

**Comment by lkeijser** [comment]
Done!

>     why did you change "wsa_calendar" to "e7ad65e902" in irado.py? Didn't the "364b570c83" work?

Not sure. I grabbed this from the POST request when I submitted the form, so I've updated it here.

**Comment by lkeijser** [comment]
Just changed it back to the old value and that still seems to work. It looks like the value is generated randomly. I've just checked it again and this time the value was '78eb3c69a0'.

**Comment by heyajohnny** [comment]
I've just tested it all and it looks good. Thx!

**Pull request merged**
